- name: Query Host Info
  ansible.builtin.include_tasks:
    file: host-info.yaml

- name: Set Host Role
  ansible.builtin.uri:
    body:
      host_role: "{{ hostvars[item.host].api_node_type }}"
    body_format: json
    headers:
      Authorization: "Bearer {{ access_token.json.access_token }}"
    method: PATCH
    status_code: 201
    url: "{{ api_infra_envs_url + infra_env_id }}/hosts/{{ item.id }}"
  loop: "{{ _assisted_host_info }}"
