- name: Generate Access Token
  ansible.builtin.uri:
    body:
      client_id: rhsm-api
      grant_type: refresh_token
      refresh_token: "{{ offline_token }}"
    body_format: form-urlencoded
    method: POST
    url: "{{ redhat_sso_url }}"
  register: access_token

- name: Update Cluster Networking
  ansible.builtin.uri:
    body: "{{ lookup('ansible.builtin.template', 'templates/network.j2') }}"
    body_format: json
    headers:
      Authorization: "Bearer {{ access_token.json.access_token }}"
    method: PATCH
    status_code: 201
    url: "{{ api_clusters_url + cluster_id }}"
