- name: Generate Access Token
  ansible.builtin.uri:
    body:
      client_id: rhsm-api
      grant_type: refresh_token
      refresh_token: "{{ offline_token }}"
    body_format: form-urlencoded
    method: POST
    url: "{{ redhat_sso_url }}"
  register: access_token

- name: Lookup Cluster ID
  ansible.builtin.set_fact:
    cluster_id: "{{ lookup('ansible.builtin.file', assisted_installer.artifact_directory + '/cluster-id') }}"

- name: Query Cluster Subscription Information
  ansible.builtin.uri:
    headers:
      Authorization: "Bearer {{ access_token.json.access_token }}"
    method: GET
    status_code: 200
    url: "{{ api_subscriptions_url }}?search=(cluster_id='{{ cluster_id }}')"
  register: api_subscription_results

- name: Debug api_subscription_results
  ansible.builtin.debug:
    var: api_subscription_results

- name: Subscribe Cluster
  ansible.builtin.uri:
    body:
      isValid: true
      support_level: "Standard"
      usage: "Development/Test"
      service_level: "L1-L3"
      system_units: "Cores/vCPU"
      cluster_billing_model: "standard"
    body_format: json
    headers:
      Authorization: "Bearer {{ access_token.json.access_token }}"
    method: PATCH
    status_code: 200
    url: "{{ api_subscriptions_url + api_subscription_results.json['items'][0].id }}"
  register: api_subscribe_results

- name: Debug api_subscribe_results
  ansible.builtin.debug:
    var: api_subscribe_results
