- name: Apply Infrastructure Node Labels/Taints
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        labels: "{{ infra_labels }}"
        name: "{{ item }}.{{ assisted_installer.base_domain }}"
      spec:
        taints: "{{ infra_taints }}"
    merge_type: strategic-merge
    state: patched
  loop: "{{ groups[provision_group] }}"
  when:
    - hostvars[item].node is defined
    - hostvars[item].node.infra is defined
    - hostvars[item].node.infra

