- name: Configure Bastion
  become: true
  gather_facts: false
  hosts: bastion
  roles:
    - role: haproxy
      when:
        - assisted_installer.user_managed_networking is defined
        - assisted_installer.user_managed_networking

- name: Initialize VMware and Deploy Cluster
  environment:
    K8S_AUTH_KUBECONFIG: "{{ assisted_installer.artifact_directory }}/auth/kubeconfig"
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Configure DNS
      ansible.builtin.include_role:
        name: ipa

    - name: Create VMs
      ansible.builtin.include_role:
        name: vmware_assisted_installer
        tasks_from: create

    - name: Create Cluster via Assisted API
      ansible.builtin.include_role:
        name: assisted_installer
        tasks_from: create

    - name: Reconfigure and Boot Metal Nodes
      ansible.builtin.include_role:
        name: metal_assisted_installer
        tasks_from: custom-ipxe
      when:
        - hostvars | json_query('*.metal_node') | count > 0

    - name: Reconfigure and Boot VMs
      ansible.builtin.include_role:
        name: vmware_assisted_installer
        tasks_from: boot

    - name: Wait for Hosts
      ansible.builtin.include_role:
        name: assisted_installer
        tasks_from: host-wait

    - name: Assign Host Roles
      ansible.builtin.include_role:
        name: assisted_installer
        tasks_from: host-role

    - name: Setup Storage
      ansible.builtin.include_role:
        name: assisted_installer
        tasks_from: storage

    - name: Setup Networking
      ansible.builtin.include_role:
        name: assisted_installer
        tasks_from: network

    - name: Start Installation
      ansible.builtin.include_role:
        name: assisted_installer
        tasks_from: install

    - name: Wait for Install
      ansible.builtin.include_role:
        name: assisted_installer
        tasks_from: install-wait

    - name: Save Credentials
      ansible.builtin.include_role:
        name: assisted_installer
        tasks_from: credentials

    - name: Setup Provider Credentials
      ansible.builtin.include_role:
        name: vmware_assisted_installer
        tasks_from: provider-credentials
      when:
        - assisted_installer.platform_type == "vsphere"

    - name: Apply Cluster Baseline Configuration
      when:
        - gitops_baseline_apply is defined
        - gitops_baseline_apply
      block:
        - name: Deploy Sealed Secrets Controller
          ansible.builtin.include_role:
            name: sealed_secrets

        - name: Deploy Argo CD and initial Baseline App of Apps
          ansible.builtin.include_role:
            name: bootstrap
          vars:
            global_baseline_disable_charts: "{{ gitops_baseline_disable_charts | default([]) }}"
