- name: Import Create Tasks
  ansible.builtin.import_tasks:
    file: create.yaml
  when:
    - _vmware_assisted_installer_action == "create"

- name: Import Boot Tasks
  ansible.builtin.import_tasks:
    file: boot.yaml
  when:
    - _vmware_assisted_installer_action == "boot"

- name: Import Provider Credential Tasks
  ansible.builtin.import_tasks:
    file: provider-credentials.yaml
  when:
    - _vmware_assisted_installer_action == "provider-credentials"
